name: Build docker image and push to dockerhub

on: [workflow_dispatch]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-task:latest .

      - name: Push docker image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-task:latest